name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:
  build_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Get Date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/chat-with-hal:latest
            ${{ secrets.DOCKER_USERNAME }}/chat-with-hal:${{ steps.date.outputs.today }}
